apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kxts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kxts
    app.kubernetes.io/part-of: tkrw-pr712-0075-0063-app
  name: devfile-sample-kxts
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kxts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kxts
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-kxts@sha256:62a38d64fcd838f0ebfb84de2c5292b12ce83a2e3721cfa5a497bb53429d82ef
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
