apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kxts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-kxts@sha256:62a38d64fcd838f0ebfb84de2c5292b12ce83a2e3721cfa5a497bb53429d82ef
        name: my-nodejs
        resources: {}
status: {}
